src/Entity/Orders.php
<?php

namespace App\Entity;

use App\Repository\OrdersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: OrdersRepository::class)]
class Orders
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'relation_users_orders')]
    private ?Users $user = null;

   
    
    #[Assert\Length(
        min: 5,
        max: 5,
        minMessage: 'Le numéro de commande doit faire au minimum {{ limit }} caractères',
        maxMessage: 'Le numéro de commande doit faire au maximum {{ limit }} caractères',
    )]
    #[Assert\Regex(
        pattern: '/^[0-9]+$/i',
        htmlPattern: '^[0-9]+$'
    )]
    #[Assert\PositiveOrZero]
    #[ORM\Column(length: 5)]
    private ?string $order_number = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    /**
     * @var Collection<int, ProductsOrders>
     */
    #[ORM\OneToMany(targetEntity: ProductsOrders::class, mappedBy: 'order', orphanRemoval: true)]
    private Collection $productsOrders;

    public function __construct()
    {
        $this->productsOrders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(?Users $user): static
    {
        $this->user = $user;

        return $this;
    }
   

    public function getOrderNumber(): ?string
    {
        return $this->order_number;
    }

    public function setOrderNumber(string $order_number): static
    {
        $this->order_number = $order_number;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    /**
     * @return Collection<int, ProductsOrders>
     */
    public function getProductsOrders(): Collection
    {
        return $this->productsOrders;
    }

    public function addProductsOrder(ProductsOrders $productsOrder): static
    {
        if (!$this->productsOrders->contains($productsOrder)) {
            $this->productsOrders->add($productsOrder);
            $productsOrder->setOrder($this);
        }

        return $this;
    }

    public function removeProductsOrder(ProductsOrders $productsOrder): static
    {
        if ($this->productsOrders->removeElement($productsOrder)) {
            // set the owning side to null (unless already changed)
            if ($productsOrder->getOrder() === $this) {
                $productsOrder->setOrder(null);
            }
        }

        return $this;
    }
}

src/Form/OrdersType.php
<?php

namespace App\Form;

use App\Entity\Orders;
use App\Entity\Products;
use App\Entity\Users;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrdersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('order_number')
            ->add('date', null, [
                'widget' => 'single_text',
            ])
            ->add('user', EntityType::class, [
                'class' => Users::class,
                'choice_label' => 'id',
            ])
            ->add('products', EntityType::class, [
                'class' => Products::class,
                'choice_label' => 'id',
                'multiple' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Orders::class,
        ]);
    }
}

src/Controller/OrdersController.php
<?php

namespace App\Controller;

use App\Entity\Cart;
use App\Entity\Orders;
use App\Entity\ProductsOrders;
use App\Form\OrdersType;
use App\Repository\CartRepository;
use App\Repository\OrdersRepository;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Validator\Constraints\Date;

class OrdersController extends AbstractController
{
    #[Route('/neword', name: 'app_orders_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $order = new Orders();
        $form = $this->createForm(OrdersType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($order);
            $entityManager->flush();

            return $this->redirectToRoute('app_orders_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('orders/new.html.twig', [
            'order' => $order,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_orders_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Orders $order, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(OrdersType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_orders_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('orders/edit.html.twig', [
            'order' => $order,
            'form' => $form,
        ]);
    }

    #[Route('/placeorder', name: 'app_orders_place', methods: ['GET'])]
    public function placeOrder(EntityManagerInterface $entityManager, Request $request): Response
    {
        $user = $this->getUser();

        $cartRepository = $entityManager->getRepository(Cart::class);

        $cartItems = $cartRepository->findBy(['user' => $user]);

        if ($cartItems == []) {
            return $this->redirectToRoute('app_home');
        }

        $order = new Orders();

        foreach ($cartItems as $cartItem) {
        
            $product = $cartItem->getProducts();

            $productOrder = new ProductsOrders();

            $productOrder->setQuantity($cartItem->getQuantity());
            $productOrder->setOrder($order);
            $productOrder->setProduct($product);
            $entityManager->remove($cartItem);
            $entityManager->persist($productOrder);
        }

        $order->setOrderNumber(rand(10000, 99999));
        $order->setDate(new DateTime());

        $order->setUser($user);

        $entityManager->persist($order);

        $entityManager->flush();

        $this->addFlash('success', "Votre commande a bien été passée !");
        return $this->redirectToRoute('app_home');
    }
}

templates/orders/_delete_form.html.twig
<form method="post" action="{{ path('app_orders_delete', {'id': order.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ order.id) }}">
    <button class="btn">Delete</button>
</form>

templates/orders/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Orders{% endblock %}

{% block body %}
    <h1>Edit Orders</h1>

    {{ include('orders/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_orders_index') }}">back to list</a>

    {{ include('orders/_delete_form.html.twig') }}
{% endblock %}

templates/orders/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Orders index{% endblock %}

{% block body %}
    <h1>Orders index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Order_number</th>
                <th>Date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.orderNumber }}</td>
                <td>{{ order.date ? order.date|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_orders_show', {'id': order.id}) }}">show</a>
                    <a href="{{ path('app_orders_edit', {'id': order.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_orders_new') }}">Create new</a>
{% endblock %}

templates/orders/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Orders{% endblock %}

{% block body %}
    <h1>Create new Orders</h1>

    {{ include('orders/_form.html.twig') }}

    <a href="{{ path('app_orders_index') }}">back to list</a>
{% endblock %}

templates/orders/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Orders{% endblock %}

{% block body %}
    <h1>Orders</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ order.id }}</td>
            </tr>
            <tr>
                <th>Order_number</th>
                <td>{{ order.orderNumber }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ order.date ? order.date|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_orders_index') }}">back to list</a>

    <a href="{{ path('app_orders_edit', {'id': order.id}) }}">edit</a>

    {{ include('orders/_delete_form.html.twig') }}
{% endblock %}