src/Entity/CustomersIdea.php
<?php

namespace App\Entity;

use App\Repository\CustomersIdeaRepository;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CustomersIdeaRepository::class)]
class CustomersIdea
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 32)]
    #[Assert\Length(
        min: 3,
        max: 32,
        minMessage: 'Votre prénom doit faire au minimum {{ limit }} caractères',
        maxMessage: 'Votre prénom doit faire au maximum {{ limit }} caractères',
    )]
    #[Assert\Regex(
        pattern: '/^[a-zA-Z0-9]+$/i',
        htmlPattern: '^[a-zA-Z0-9]+$'
    )]
    private ?string $first_name = null;

    #[ORM\Column(length: 32)]
    #[Assert\Length(
        min: 2,
        max: 32,
        minMessage: 'Votre nom doit faire au minimum {{ limit }} caractères',
        maxMessage: 'Votre nom doit faire au maximum {{ limit }} caractères',
    )]
    #[Assert\Regex(
        pattern: '/^[a-zA-Z0-9]+$/i',
        htmlPattern: '^[a-zA-Z0-9]+$'
    )]
    private ?string $last_name = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(
        min: 4,
        max: 180,
        minMessage: 'Votre email doit faire au minimum {{ limit }} caractères',
        maxMessage: 'Votre email doit faire au maximum {{ limit }} caractères',
    )]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(
        min: 1,
        max: 256,
        minMessage: 'Votre message doit faire au minimum {{ limit }} caractères',
        maxMessage: 'Votre message doit faire au maximum {{ limit }} caractères',
    )]
    private ?string $message = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): static
    {
        $this->message = $message;

        return $this;
    }
}

src/Form/CustomersIdeaType.php
<?php

namespace App\Form;

use App\Entity\CustomersIdea;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CustomersIdeaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('first_name')
            ->add('last_name')
            ->add('email')
            ->add('message')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => CustomersIdea::class,
        ]);
    }
}

src/Controller/CustomersIdeaController.php
<?php

namespace App\Controller;

use App\Entity\CustomersIdea;
use App\Form\CustomersIdeaType;
use App\Repository\CustomersIdeaRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;


class CustomersIdeaController extends AbstractController
{
    #[Route('/newcustomeridea', name: 'app_customers_idea_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $customersIdea = new CustomersIdea();
        $form = $this->createForm(CustomersIdeaType::class, $customersIdea);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($customersIdea);
            $entityManager->flush();

            return $this->redirectToRoute('app_customers_idea_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('customers_idea/new.html.twig', [
            'customers_idea' => $customersIdea,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_customers_idea_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, CustomersIdea $customersIdea, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CustomersIdeaType::class, $customersIdea);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_customers_idea_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('customers_idea/edit.html.twig', [
            'customers_idea' => $customersIdea,
            'form' => $form,
        ]);
    }

    #[Route('/submitanidea', name: 'app_customers_idea_submit')]
    public function createThread(Request $request, EntityManagerInterface $entityManager): Response
    {
        $customersIdea = new CustomersIdea();

        $customersIdeaForm = $this->createForm(CustomersIdeaType::class, $customersIdea);

        $customersIdeaForm->handleRequest($request);


        if ($customersIdeaForm->isSubmitted() && $customersIdeaForm->isValid()) {

            $entityManager->persist($customersIdea);
            $entityManager->flush();
            $this->addFlash('success', "Votre suggestion a bien été envoyée !");
            return $this->redirectToRoute('app_home');
        }

        
        return $this->render('customers_idea/customersIdeaForm.html.twig', [
            'customersIdeaForm' => $customersIdeaForm
        ]);
    }
}

templates/customers_idea/_delete_form.html.twig
<form method="post" action="{{ path('app_customers_idea_delete', {'id': customers_idea.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ customers_idea.id) }}">
    <button class="btn">Delete</button>
</form>

templates/customers_idea/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/customers_idea/customersIdeaForm.html.twig
{% extends 'base.html.twig' %}

{% block title %}CubeDesign - Soumettre une idée
{% endblock %}

{% block body %}


	<section class="flex justify-center items-center mt-20">
    <div class="flex justify-start items-start">
		{{ form_errors(customersIdeaForm) }}

            {{ form_start(customersIdeaForm, {'attr': {'class': 'space-y-6'}}) }}
			<div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 pr-20">
			<h2 class="h3 mb-3 mt-6 font-weight-normal">Nous contacter</h2>
                <div class="mb-6 text-sm">
                    {{ form_label(customersIdeaForm.first_name, 'Prénom', {'label_attr': {'class': 'block text-gray-700 font-bold mb-2'}}) }}
                    {{ form_widget(customersIdeaForm.first_name, {'attr': {'class': 'shadow appearance-none w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline', 'placeholder': 'prénom'}}) }}
                </div>
                <div class="mb-6 text-sm">
                    {{ form_label(customersIdeaForm.last_name, 'Nom', {'label_attr': {'class': 'block text-gray-700 font-bold mb-2'}}) }}
                    {{ form_widget(customersIdeaForm.last_name, {'attr': {'class': 'shadow appearance-none w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline', 'placeholder': 'nom'}}) }}
                </div>
                <div class="mb-6 text-sm">
                    {{ form_label(customersIdeaForm.email, 'Email', {'label_attr': {'class': 'block text-gray-700 font-bold mb-2'}}) }}
                    {{ form_widget(customersIdeaForm.email, {'attr': {'class': 'shadow appearance-none w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline', 'placeholder': 'email'}}) }}
                </div>
                <div class="mb-6 text-sm">
                    {{ form_label(customersIdeaForm.message, 'Message', {'label_attr': {'class': 'block text-gray-700 font-bold mb-2'}}) }}
                    {{ form_widget(customersIdeaForm.message, {'attr': {'class': 'shadow appearance-none w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline', 'placeholder': 'message'}}) }}
                </div class="mb-6 text-sm">
              

                <button type="submit" class="bg-amber-500 hover:bg-amber-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Envoyer</button>
				</div>
            {{ form_end(customersIdeaForm) }}
    </div>
</section>


{% endblock %}

templates/customers_idea/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit CustomersIdea{% endblock %}

{% block body %}
    <h1>Edit CustomersIdea</h1>

    {{ include('customers_idea/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_customers_idea_index') }}">back to list</a>

    {{ include('customers_idea/_delete_form.html.twig') }}
{% endblock %}

templates/customers_idea/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}CustomersIdea index{% endblock %}

{% block body %}
    <h1>CustomersIdea index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>First_name</th>
                <th>Last_name</th>
                <th>Email</th>
                <th>Message</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for customers_idea in customers_ideas %}
            <tr>
                <td>{{ customers_idea.id }}</td>
                <td>{{ customers_idea.firstName }}</td>
                <td>{{ customers_idea.lastName }}</td>
                <td>{{ customers_idea.email }}</td>
                <td>{{ customers_idea.message }}</td>
                <td>
                    <a href="{{ path('app_customers_idea_show', {'id': customers_idea.id}) }}">show</a>
                    <a href="{{ path('app_customers_idea_edit', {'id': customers_idea.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_customers_idea_new') }}">Create new</a>
{% endblock %}

templates/customers_idea/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New CustomersIdea{% endblock %}

{% block body %}
    <h1>Create new CustomersIdea</h1>

    {{ include('customers_idea/_form.html.twig') }}

    <a href="{{ path('app_customers_idea_index') }}">back to list</a>
{% endblock %}

templates/customers_idea/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}CustomersIdea{% endblock %}

{% block body %}
    <h1>CustomersIdea</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ customers_idea.id }}</td>
            </tr>
            <tr>
                <th>First_name</th>
                <td>{{ customers_idea.firstName }}</td>
            </tr>
            <tr>
                <th>Last_name</th>
                <td>{{ customers_idea.lastName }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ customers_idea.email }}</td>
            </tr>
            <tr>
                <th>Message</th>
                <td>{{ customers_idea.message }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_customers_idea_index') }}">back to list</a>

    <a href="{{ path('app_customers_idea_edit', {'id': customers_idea.id}) }}">edit</a>

    {{ include('customers_idea/_delete_form.html.twig') }}
{% endblock %}